#!/bin/bash

set -e

patch_file=$1
android_patch_dir=$2

patch_name=${patch_file##*/}

#echo === reset: $patch_name ====
echo reset: $patch_name
cd $android_patch_dir
#git checkout .
#git clean -df
git add .
git reset --hard
#echo

