#!/bin/bash

set -e

script_dir="$(dirname "$(readlink -f "$0")")"

source $script_dir/opd-set-env

$script_dir/opd-for-each $script_dir/opd-for-each-apply

#cd $openpdroid_android_dir
#source build/envsetup.sh
#brunch <DEVICE_TARGET>

