#!/bin/bash

set -e

patch_file=$1
android_patch_dir=$2

patch_name=${patch_file##*/}

echo === apply: $patch_name ====
cd $android_patch_dir
git checkout -b openpdroid
patch -p1 --no-backup-if-mismatch <$patch_file
echo

