#!/bin/bash

set -e

patch_file=$1
android_patch_dir=$2

patch_name=${patch_file##*/}

#echo === make patch: $patch_name ====
echo make patch: $patch_name
cd $android_patch_dir
git add .
#git diff -U2 HEAD >$patch_file
git diff HEAD >$patch_file
#echo

